### ISSUE TITLE
Installation fails under Python 3 on Mac

### ISSUE THREAD

**Issue by ketch** [hplgit/preprocess#9]
I'm trying to install on a Mac (running OS X 10.12.5) under Python 3.  Installation under Python 2 succeds, but with Python 3 I get the following output:

```
» pip3 install --no-cache-dir --upgrade preprocess
Collecting preprocess
  Downloading preprocess-1.1.0.zip (59kB)
    100% |████████████████████████████████| 61kB 357kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gm/8bn6zk2d3sd3wzk60tb08y180000gn/T/pip-build-uf_gm76_/preprocess/setup.py", line 28, in <module>
        import preprocess
      File "/private/var/folders/gm/8bn6zk2d3sd3wzk60tb08y180000gn/T/pip-build-uf_gm76_/preprocess/lib/preprocess.py", line 264
        except Exception, ex:
                        ^
    SyntaxError: invalid syntax
```

**Comment by ketch** [comment]
I also tried cloning the current master branch and installing, but I get this error:

```    
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gm/8bn6zk2d3sd3wzk60tb08y180000gn/T/pip-kh4noipj-build/setup.py", line 28, in <module>
        import preprocess
      File "/private/var/folders/gm/8bn6zk2d3sd3wzk60tb08y180000gn/T/pip-kh4noipj-build/lib/preprocess.py", line 136, in <module>
        from past.builtins import cmp
    ImportError: No module named 'past'
```

**Comment by johannesring** [comment]
Try this one instead: https://github.com/doconce/preprocess

**Comment by ketch** [comment]
That worked; thanks!  Perhaps a release from that fork should be put on PyPi?

**Comment by johannesring** [comment]
Yes, it should. Maybe you can register an [issue](https://github.com/doconce/preprocess/issues) for this?

**Comment by ketch** [comment]
I'm confused -- why open another issue when we already have this one?
